export const SERVICE_STATUS = {
  ACTIVE: 'Active',
  MAINTENANCE: 'Under Maintenance',
};

export const SERVICES = [
  {
    id: 'n8n',
    title: 'n8n',
    description: 'Workflow automation platform',
    path: '/data/apps/automation/n8n',
    icon: '⚙️',
    category: 'Automation & APIs',
    status: SERVICE_STATUS.ACTIVE,
    featured: true,
  },
  {
    id: 'redis',
    title: 'Redis',
    description: 'In-memory data store',
    path: '/data/apps/databases/redis',
    icon: '🔴',
    category: 'Automation & APIs',
    status: SERVICE_STATUS.ACTIVE,
    adminOnly: true,
  },
  {
    id: 'postgres',
    title: 'Postgres',
    description: 'PostgreSQL database',
    path: '/data/apps/databases/postgres',
    icon: '🐘',
    category: 'Automation & APIs',
    status: SERVICE_STATUS.ACTIVE,
    adminOnly: true,
  },
  {
    id: 'homeassistant',
    title: 'Home Assistant',
    description: 'Home automation platform',
    path: '/data/apps/smart-home/homeassistant',
    icon: '🏡',
    category: 'Smart Home',
    status: SERVICE_STATUS.ACTIVE,
    featured: true,
  },
  {
    id: 'mqtt',
    title: 'Mosquitto MQTT',
    description: 'MQTT message broker',
    path: '/data/apps/smart-home/mqtt',
    icon: '📡',
    category: 'Smart Home',
    status: SERVICE_STATUS.ACTIVE,
  },
  {
    id: 'zigbee2mqtt',
    title: 'Zigbee2MQTT',
    description: 'Zigbee to MQTT bridge',
    path: '/data/apps/smart-home/zigbee2mqtt',
    icon: '📶',
    category: 'Smart Home',
    status: SERVICE_STATUS.ACTIVE,
  },
  {
    id: 'esphome',
    title: 'ESPHome',
    description: 'ESP device management',
    path: '/data/apps/smart-home/esphome',
    icon: '💡',
    category: 'Smart Home',
    status: SERVICE_STATUS.MAINTENANCE,
  },
  {
    id: 'kallithea',
    title: 'Kallithea',
    description: 'Source code management',
    path: '/data/apps/vcs/kallithea',
    icon: '📦',
    category: 'Version Control',
    status: SERVICE_STATUS.ACTIVE,
  },
  {
    id: 'repositories',
    title: 'Repositories',
    description: 'Git repositories',
    path: '/data/repos',
    icon: '📁',
    category: 'Version Control',
    status: SERVICE_STATUS.ACTIVE,
    adminOnly: true,
  },
  {
    id: 'jellyfin',
    title: 'Jellyfin',
    description: 'Media streaming server',
    path: '/data/apps/media/jellyfin',
    icon: '🎬',
    category: 'Media',
    status: SERVICE_STATUS.ACTIVE,
    featured: true,
  },
  {
    id: 'navidrome',
    title: 'Navidrome',
    description: 'Music streaming server',
    path: '/data/apps/media/navidrome',
    icon: '🎵',
    category: 'Media',
    status: SERVICE_STATUS.ACTIVE,
  },
  {
    id: 'media-content',
    title: 'Media Content',
    description: 'Media files management',
    path: '/data/media',
    icon: '💾',
    category: 'Media',
    status: SERVICE_STATUS.ACTIVE,
    adminOnly: true,
  },
  {
    id: 'grafana',
    title: 'Grafana',
    description: 'Metrics visualization',
    path: '/data/apps/monitoring/grafana',
    icon: '📈',
    category: 'Monitoring',
    status: SERVICE_STATUS.ACTIVE,
    adminOnly: true,
  },
  {
    id: 'ntfy',
    title: 'ntfy',
    description: 'Push notifications',
    path: '/data/apps/monitoring/ntfy',
    icon: '🔔',
    category: 'Monitoring',
    status: SERVICE_STATUS.ACTIVE,
  },
];
